version: "3.9"
services:
  tests:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - synapse
  synapse:
    image: "matrixdotorg/synapse"
    entrypoint: ["/data/start.sh"]
    volumes:
      - ./synapse/data:/data
    ports:
      - "8008:8008"
    logging:
      driver: none
